### ISSUE TITLE
Status response

### ISSUE THREAD

**Issue by ScottProkopetz** [roblans/Blu4Net#10]
Hi Rob,
I've noticed the PlayerMedia class does not capture all of the response attributes from the Status request. Is there a reason for that or did you only capture the ones that seemed important at the time?

Also, I may be missing something but can't seem to find a way to call GetStatus() from the the BluPlayer object to get the entire status response. Is this by design or am I using the wrong object?  The only way I can do this is by creating another BluChannel and calling GetStatus() and then getting values of the fields from the Result, but is this the right way to accomplish this?

Thanks,
Scott.

**Comment by roblans** [comment]
Hi Scott,
Yes, I only used the values from the status message that were relevant to me. If there are values that your missing just let me know and I will add them (or make the changes yourself and send me a pull-request)

Indeed it is by design that you can’t get the compleet status through the BluPlayer object. Again, if you miss anything please let me know.
